[package]
name = "carmy-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Command-line tool for Carmy applications"

[[bin]]
name = "carmy"
path = "src/main.rs"

[dependencies]
